### ISSUE TITLE
Provide code/instructions to validate CF script locally

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/scicomp-provisioner#161]
It'd be nice to include the relevant scripts (with some usage instructions) in this repo or somewhere easily accessible such that users could check their YAML file and debug any problems _before_ creating a PR.

It looks like some of the scripts are
```yaml
jobs:
  include:
    - stage: validate
      script:
        - yamllint ./config ./templates
        - ./lint_stack.sh -l ./config/prod
        - cfn-lint ./templates/**/*
```

It looks like some of the scripts (or at least `lint_stack.sh` are in [this repo](https://github.com/Sage-Bionetworks/infra-utils). Some of the inputs might need to be reconfigured as URLs instead of relative paths. Not sure if there are other dependencies that would be needed...
